docking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *
from .import views

app_name = "abampdb"
urlpatterns = [
    path('',views.IndexPage,name='index'),
    path('enter/',views.EnterPage,name='enter'),
    path("home/", views.search_view, name="home"),
    path("<int:proteins_id>", views.protein, name='protein'),
    path('search/', views.search_view, name='search'),   
    path('create_protien/', views.create_protien, name='create_protein'),
    path('<int:proteins_id>/target_proteins', views.target_proteins, name='target_proteins'),
    path('serve-pdb/<int:dock_id>/', views.serve_amp_pdb, name='serve_pdb'),
    path("stats/", views.StatsPage, name="stats"),
    path("about/", views.AboutUsPage, name="about_us"),
    path("tutorial/", views.TutorialPage, name="tutorial"),
    path("contact/", views.ContactView.as_view(), name="contact"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# path("docking/", views.get_search_results, name="docking"),

paampdb/urls.py
from django.contrib import admin
from django.urls import path
from docking import views

app_name = "paampdb"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexPage,name='index'),
    path('enter/',views.EnterPage,name='enter'),
    path("home/", views.search_view, name="home"),
    path('protein/<int:proteins_id>/', views.protein, name='protein'),
    path('search/', views.search_view, name='search'),   
    path('create_protien/', views.create_protein, name='create_protein'),
    #path('amp/<int:amp_id>/target/<int:target_protein_id>/', views.dock_complexes, name='dock_complexes'),
    #path('target_proteins/', views.target_proteins, name='target_proteins'),
    path("stats/", views.StatsPage, name="stats"),
    path("about/", views.AboutUsPage, name="about_us"),
    path("tutorial/", views.TutorialPage, name="tutorial"),
    path("contact/", views.ContactView.as_view(), name="contact"),

]

docking/models.py
from django.db import models


class TargetProtein(models.Model):
    target_protein = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.target_protein

class AMP(models.Model):
    target_protein = models.ForeignKey(TargetProtein, on_delete=models.SET_NULL, null=True, blank=True)
    amp_no = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=255)
    sequence = models.TextField()
    source = models.CharField(max_length=255)
    tiny_number = models.IntegerField()
    small_number = models.IntegerField()
    aliphatic_number = models.IntegerField()
    aromatic_number = models.IntegerField()
    nonpolar_number = models.IntegerField()
    polar_number = models.IntegerField()
    charged_number = models.IntegerField()
    basic_number = models.IntegerField()
    acidic_number = models.IntegerField()
    tiny_mole = models.FloatField()
    small_mole = models.FloatField()
    aliphatic_mole = models.FloatField()
    aromatic_mole = models.FloatField()
    nonpolar_mole = models.FloatField()
    polar_mole = models.FloatField()
    charged_mole = models.FloatField()
    basic_mole = models.FloatField()
    acidic_mole = models.FloatField()
    molecular_weight = models.CharField(max_length=50)
    length = models.IntegerField()
    isoelectric_point = models.CharField(max_length=50)
    aliphatic_index = models.FloatField()
    antigenic = models.CharField(max_length=255)
    toxicity = models.CharField(max_length=255)
    cpp = models.CharField(max_length=255)
    charge = models.CharField(max_length=50)
    instability_index = models.CharField(max_length=50)
    hydrophobicity = models.CharField(max_length=50)
    hydrophobic_moment = models.CharField(max_length=50)
    boman_index = models.CharField(max_length=50)
    hp = models.CharField(max_length=50)
    antimicrobial = models.CharField(max_length=255)
    half_life = models.CharField(max_length=255)
    pdb_name = models.CharField(("PDBName"), max_length=1000)
    pdb_file = models.FileField(upload_to='amp_pdb_files/', null=True, blank=True)

    def __str__(self):
        return self.name

class Dock(models.Model):
    amp = models.ForeignKey(AMP, on_delete=models.CASCADE)
    target_protein = models.ForeignKey(TargetProtein, on_delete=models.CASCADE)
    dock = models.CharField(max_length=255)
    pdb_structure = models.FileField(upload_to='dock_pdb_files/', null=True, blank=True)
    pdb_structure_name = models.CharField(max_length=1000)
    avg_rmsd = models.CharField(max_length=50)
    lowest_rmsd = models.CharField(max_length=50)
    binding_energy = models.CharField(max_length=50)
    ligplot = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.amp} - {self.target_protein} - {self.dock}"
    

class PDBQuery(models.Model):
    query_id = models.CharField(max_length=1000)
    # email = models.CharField(max_length=200)

    def __str__(self):
        return self.query_id

class PDBTQuery(models.Model):
    query_id = models.CharField(max_length=1000)
    # email = models.CharField(max_length=200)

    def __str__(self):
        return self.query_id

class PDBDQuery(models.Model):
    query_id = models.CharField(max_length=1000)
    # email = models.CharField(max_length=200)

    def __str__(self):
        return self.query_id

docking/forms.py
# forms.py
from django import forms
from .models import AMP, TargetProtein, Dock
class SearchForm(forms.Form):
    amp = forms.ModelChoiceField(queryset=AMP.objects.all())
    target_proteins = forms.ModelMultipleChoiceField(queryset=TargetProtein.objects.all())

docking/views.py
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models import Q
from django.views.generic import ListView, TemplateView, FormView
from .models import PDBQuery, AMP, TargetProtein, Dock
import os

def EnterPage(request):
    return render(request, "search.html")

def IndexPage(request):
    return render(request, "index.html")

def AboutUsPage(request):
    return render(request, "about_us.html")

def StatsPage(request):
    return render(request, "stats.html")

class ContactView(generic.TemplateView):
    """Contact section of the AMPdb tool."""
    model = PDBQuery
    template_name = "contact.html"

def TutorialPage(request):
    return render(request, 'tutorial.html')

def search_view(request):
    return render(request, "search.html", {
        "targets": TargetProtein.objects.all(),
        "proteins": AMP.objects.all()
    })

def protein(request, proteins_id):
    protein = get_object_or_404(AMP, pk=proteins_id)
    target_protein = protein.target_protein
    dock = Dock.objects.filter(amp=protein, target_protein=target_protein)
    return render(request, "protein.html", {
        "protein": protein,
        "dock": dock,
    })


def create_protein(request):
    if request.method == 'POST':
        protein_id = request.POST.get('protein_id')
        protein_name = request.POST.get('protein_name')
        score = request.POST.get('score')
        sequence = request.POST.get('sequence')
        target_protein_id = request.POST.get('target_id')
        
        try:
            protein = AMP.objects.get(id=protein_id)
            protein.target_protein_id = target_protein_id
            protein.save()
            
            target_protein = TargetProtein.objects.get(id=target_protein_id)
            target_protein_name = target_protein.target_protein + '_' + protein.pdb_name[2:]
            
            dock_instances = Dock.objects.filter(dock__contains=target_protein_name)
            for dock_instance in dock_instances:
                dock_instance.target_protein.add(target_protein)
            
            redirect_url = reverse('protein', kwargs={'proteins_id': protein_id})
            return redirect(redirect_url)
        except AMP.DoesNotExist:
            messages.error(request, 'Protein not found')
            return redirect('create_protein')  # Redirect to a relevant page
        except TargetProtein.DoesNotExist:
            messages.error(request, 'Target Protein not found')
            return redirect('create_protein')  # Redirect to a relevant page
        except Exception as e:
            messages.error(request, f'An error occurred: {str(e)}')
            return redirect('create_protein')  # Redirect to a relevant page
    else:
        return HttpResponse('Invalid request method')

docking/templates/about_us.html
{% extends 'base.html' %} {% block content %} {% load static %}

<head>
    <title>Font Awesome Icons</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<style>
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {}
    
    a,
    a:hover,
    a:focus,
    a:active {
        text-decoration: none;
        outline: none;
    }
    
    a,
    a:active,
    a:focus {
        color: #6f6f6f;
        text-decoration: none;
        transition-timing-function: ease-in-out;
        -ms-transition-timing-function: ease-in-out;
        -moz-transition-timing-function: ease-in-out;
        -webkit-transition-timing-function: ease-in-out;
        -o-transition-timing-function: ease-in-out;
        transition-duration: .2s;
        -ms-transition-duration: .2s;
        -moz-transition-duration: .2s;
        -webkit-transition-duration: .2s;
        -o-transition-duration: .2s;
    }
    
    ul {
        margin: 0;
        padding: 0;
        list-style: none;
    }
    
    img {
        max-width: 100%;
        height: auto;
    }
    
    section {
        padding: 60px 0;
        /* min-height: 100vh;*/
    }
    
    .sec-title {
        position: relative;
        z-index: 1;
        margin-bottom: 60px;
    }
    
    .sec-title .title {
        position: relative;
        display: block;
        font-size: 18px;
        line-height: 24px;
        color: #00aeef;
        font-weight: 500;
        margin-bottom: 15px;
    }
    
    .sec-title h2 {
        position: relative;
        display: block;
        font-size: 40px;
        line-height: 1.28em;
        color: #222222;
        font-weight: 600;
        padding-bottom: 18px;
    }
    
    .sec-title h2:before {
        position: absolute;
        content: '';
        left: 0px;
        bottom: 0px;
        width: 50px;
        height: 3px;
        background-color: #d1d2d6;
    }
    
    .sec-title .text {
        position: relative;
        font-size: 16px;
        line-height: 26px;
        color: #848484;
        font-weight: 400;
        margin-top: 35px;
    }
    
    .sec-title.light h2 {
        color: #ffffff;
    }
    
    .sec-title.text-center h2:before {
        left: 50%;
        margin-left: -25px;
    }
    
    .list-style-one {
        position: relative;
    }
    
    .list-style-one li {
        position: relative;
        font-size: 16px;
        line-height: 26px;
        color: #222222;
        font-weight: 400;
        padding-left: 35px;
        margin-bottom: 12px;
    }
    
    .list-style-one li:before {
        content: "\f058";
        position: absolute;
        left: 0;
        top: 0px;
        display: block;
        font-size: 18px;
        padding: 0px;
        color: #ff2222;
        font-weight: 600;
        -moz-font-smoothing: grayscale;
        -webkit-font-smoothing: antialiased;
        font-style: normal;
        font-variant: normal;
        text-rendering: auto;
        line-height: 1.6;
        font-family: "Font Awesome 5 Free";
    }
    
    .list-style-one li a:hover {
        color: #44bce2;
    }
    
    .btn-style-one {
        position: relative;
        display: inline-block;
        font-size: 17px;
        line-height: 30px;
        color: #ffffff;
        padding: 10px 30px;
        font-weight: 600;
        overflow: hidden;
        letter-spacing: 0.02em;
        background-color: #35718A;
    }
    
    .btn-style-one:hover {
        background-color: #0794c9;
        color: #ffffff;
    }
    
    .about-section {
        position: relative;
        padding: 250px 0 70px;
    }
    
    .about-section .sec-title {
        margin-bottom: 45px;
    }
    
    .about-section .content-column {
        position: relative;
        margin-bottom: 50px;
    }
    
    .about-section .content-column .inner-column {
        position: relative;
        padding-left: 30px;
    }
    
    .about-section .text {
        margin-bottom: 20px;
        font-size: 16px;
        line-height: 26px;
        color: #848484;
        font-weight: 400;
    }
    
    .about-section .list-style-one {
        margin-bottom: 45px;
    }
    
    .about-section .btn-box {
        position: relative;
    }
    
    .about-section .btn-box a {
        padding: 15px 50px;
    }
    
    .about-section .image-column {
        position: relative;
    }
    
    .about-section .image-column .text-layer {
        position: absolute;
        right: -110px;
        top: 50%;
        font-size: 325px;
        line-height: 1em;
        color: #ffffff;
        margin-top: -175px;
        font-weight: 500;
    }
    
    .about-section .image-column .inner-column {
        position: relative;
        padding-left: 80px;
        padding-bottom: 0px;
    }
    
    .about-section .image-column .inner-column .author-desc {
        position: absolute;
        bottom: 16px;
        z-index: 1;
        background: orange;
        padding: 10px 15px;
        left: 96px;
        width: calc(100% - 152px);
        border-radius: 50px;
    }
    
    .about-section .image-column .inner-column .author-desc h2 {
        font-size: 21px;
        letter-spacing: 1px;
        text-align: center;
        color: #fff;
        margin: 0;
    }
    
    .about-section .image-column .inner-column .author-desc span {
        font-size: 16px;
        letter-spacing: 6px;
        text-align: center;
        color: #fff;
        display: block;
        font-weight: 400;
    }
    
    .about-section .image-column .inner-column:before {
        content: '';
        position: absolute;
        width: calc(50% + 80px);
        height: calc(100% + 160px);
        top: -80px;
        left: 0px;
        background: transparent;
        z-index: 0;
        border: 44px solid #343a40;
    }
    
    .about-section .image-column .image-1 {
        position: relative;
    }
    
    .about-section .image-column .image-2 {
        position: absolute;
        left: 0;
        bottom: 0;
    }
    
    .about-section .image-column .image-2 img,
    .about-section .image-column .image-1 img {
        box-shadow: 0 30px 50px rgba(8, 13, 62, .15);
        border-radius: 46px;
    }
    
    .about-section .image-column .video-link {
        position: absolute;
        left: 70px;
        top: 170px;
    }
    
    .about-section .image-column .video-link .link {
        position: relative;
        display: block;
        font-size: 22px;
        color: #191e34;
        font-weight: 400;
        text-align: center;
        height: 100px;
        width: 100px;
        line-height: 100px;
        background-color: #ffffff;
        border-radius: 50%;
        box-shadow: 0 30px 50px rgba(8, 13, 62, .15);
        -webkit-transition: all 300ms ease;
        -moz-transition: all 300ms ease;
        -ms-transition: all 300ms ease;
        -o-transition: all 300ms ease;
        transition: all 300ms ease;
    }
    
    .about-section .image-column .video-link .link:hover {
        background-color: #191e34;
        color: #fff
    }
    
    div {
        text-align: justify;
        text-justify: inter-word;
    }
    
    h2 {
        text-align: center;
        text-justify: inter-word;
    }
    
    title {
        text-align: center;
        text-justify: inter-word;
    }
    
    section {
        padding: 0;
    }
</style>

<section class="about-section">

    <div class="container">
        <div class="row">
            <div class="content-column col-lg-6 col-md-12 col-sm-12 order-2">
                <div class="inner-column">
                    <div class="sec-title">

                        <h3>Microbial Genomics & Bioinformatics Research Group (MGB)</h3>
                    </div>
                    <div class="text">We are based at Atta-ur-Rahman School of Applied Biosciences (ASAB), National University of Sciences and Technology (NUST), a lush green campus in the beautiful Capital City Islamabad. Our group is mainly focusing on integrative genomics
                        approaches; producing and analyzing the public genomic data for studying the genomic epidemiology, evolution and transmission (genetic exchanges) in bacterial pathogens. We are particularly interested in the regional crisis of
                        growing antimicrobial resistance (AMR) and dissemination of multidrug resistant pathogens both at the community and healthcare settings, we are also like to develop tools and databases for pathogen genomic data analysis, prospective
                        surveillance and tracking of emerging pathogens in the environment and clinical settings using whole genome sequencing and bioinformatics analysis. Employing reverse vaccinology and machine learning approaches for prediction of
                        potential immunogenic and therapeutic targets (vaccines and drugs)..
                        <p>For more information about our lab and current research projects, please visit our <a href="https://mgbio.asab.nust.edu.pk/">website https://mgbio.asab.nust.edu.pk/</a>.</p>
                    </div>
                    <div class="btn-box">
                        <a href="{% url 'contact' %}" class="theme-btn btn-style-one">Contact Us</a>
                    </div>
                </div>
            </div>

            <!-- Image Column -->
            <div class="image-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column wow fadeInLeft">
                    <div class="author-desc">
                        <h2>IBG-Group</h2>
                    </div>
                    <figure class="image-1">
                        <a href="#" class="lightbox-image" data-fancybox="images"><img title="IBG_Lab" src="{% static 'img/IBGR.jpg' %}" alt=""></a>
                    </figure>

                </div>
            </div>

        </div>


    </div>
    </div>
</section>
{% endblock %}
<!-- 
    <h2>
        About Us
    </h2>

    <p class="text-justify">
        AbAMPdb is an open repository to screen potential antimicrobial peptides against Acinetobacter baumannii.
        Our
        current index is version 1 and searches more than 150 publications to screen 30 Potential AMPs from
        different
        resources. All the data based on AMPs and their interaction with A. baumannii Omp38 protein Uniprot ID is
        Q6RYW5
        freely available through search index and can be downloaded via available formats.
    </p>

    <h2>
        AbAMPdb Team
    </h2>

    <p class="text-justify">
        Please mention yours and also consult the order of arranging names with Dr. Tariq Saeed <br>
        Farha Anwer (PhD candidate, ASAB, NUST) <br>
        Dr. Amjad Ali (Associate Professor, ASAB, NUST) <br>
    </p>

    <h2>
        AbAMPdb Funding
    </h2>

    <p class="text-justify">
        Atta Ur Rahman School of Applied Biosciences (ASAB), NUST <br>
        Research Centre for Modelling and Simulation (RCMS), NUST
    </p>
        <center><img src="{% static 'img/nust.png' %}" width="20%" height="20%"></center> -->*/

docking/templates/contact.html
{% extends 'base.html' %} {% block content %}
<style>
    .btn-primary {
        color: #fff;
        background-color: #35718A;
        border-color: #35718A;
    }
    
    .border-primary {
        border-color: #35718A!important;
    }
    
    .bg-primary {
        background-color: #35718A!important;
    }
    
    section {
        margin-top: 200px;
        /* adjust the value as needed */
    }
    
    .input-group .form-control {
        width: 230%;
    }
    
    .my-btn-class {
        position: absolute;
        top: -50px;
        left: 45%;
        transform: translateX(-50%);
    }
</style>
<section class="container mt-4">
    <div class="row">
        <div class="col-sm-12 text-center mb-4">
            <a class="btn btn-primary my-btn-class" target="_blank" href="https://mgbio.asab.nust.edu.pk/">MgBio-Group</a>
        </div>

        <!--Grid column-->
        <div class="col-sm-12 mb-4 col-md-5">
            <!--Form with header-->
            <div class="card border-primary rounded-0">
                <div class="card-header p-0">
                    <div class="bg-primary text-white text-center py-2">
                        <h3><i class="fa fa-envelope"></i> Write to us:</h3>
                        <p class="m-0">We’ll write rarely, but only the best content.</p>
                    </div>
                </div>
                <div class="card-body p-3">

                    <div>
                        <form action="https://formspree.io/f/xgebvglr" method="POST">{% csrf_token %}
                            <label> Your name </label>
                            <div class="input-group">
                                <input value="" type="text" name="data[name]" class="form-control" id="inlineFormInputGroupUsername" placeholder="Your name">
                            </div>
                    </div>
                    <div class="form-group">
                        <label>Your email</label>
                        <div class="input-group mb-2 mb-sm-0">
                            <input type="email" value="" name="data[email]" class="form-control" id="inlineFormInputGroupUsername" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Subject</label>
                        <div class="input-group mb-2 mb-sm-0">
                            <input type="text" name="data[subject]" class="form-control" id="inlineFormInputGroupUsername" placeholder="Subject">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Message</label>
                        <div class="input-group mb-2 mb-sm-0">
                            <input type="text" class="form-control" name="mesg">
                        </div>
                    </div>
                    <div class="text-center">
                        <input type="submit" value="Submit" class="btn btn-primary btn-block rounded-0 py-2">
                        </form>
                    </div>
                </div>

            </div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-sm-12 col-md-7">
            <!--Google map-->
            <div class="mb-4">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13286.264708969926!2d72.993001!3d33.6424888!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38df9675aaaaaaab%3A0xc5180922c44eb86b!2sNational%20University%20of%20Sciences%20%26%20Technology%20(NUST)!5e0!3m2!1sen!2s!4v1674551411504!5m2!1sen!2s"
                    width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
            </iframe>
            </div>
            <!--Buttons-->
            <div class="row text-center">
                <div class="col-md-4">
                    <a class="bg-primary px-3 py-2 rounded text-white mb-2 d-inline-block"><i class="fa fa-map-marker"></i></a>
                    <p> Atta-ur-Rahman School of Applied Biosciences (ASAB) National University of Sciences & Technology (NUST) Sector H-12, Islamabad, Pakistan 44000 </p>
                </div>
                <div class="col-md-4">
                    <a class="bg-primary px-3 py-2 rounded text-white mb-2 d-inline-block"><i class="fa fa-phone"></i></a>
                    <p>+92 51 9085 6138</p>
                </div>
                <div class="col-md-4">
                    <a class="bg-primary px-3 py-2 rounded text-white mb-2 d-inline-block"><i class="fa fa-envelope"></i></a>
                    <p> amjad.ali@asab.nust.edu.pk </p>
                </div>
            </div>
        </div>
        <!--Grid column-->
    </div>
</section>
{% endblock %}

docking/templates/docks.html
{% extends './base.html' %} {% block content %}


<style>
    body {
        padding-top: 200px;
    }
</style>


<style>
    /* 
Generic Styling, for Desktops/Laptops 
*/
    
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 200px;
    }
    /* Zebra striping */
    
    tr:nth-of-type(odd) {
        background: #eee;
    }
    
    th {
        background: #333;
        color: white;
        font-weight: bold;
    }
    
    td,
    th {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }
</style>
<!--Table-->
<form class="form-inline" method="POST" action=""></form>
{% csrf_token %} {{ form.as_p }}
<table class="table table-striped w-auto">

    <!--Table head-->
    <thead>

        <tr>
            <td>
                <select id="mySelect">
	<option value="">Select an option...</option>
	{% for dock in dock_list %}
	  <option value="{{ dock.id }}">{{ dock.dock_1 }}</option>
	{% endfor %}
  </select>
            </td>
            <script>
                var selectElement = document.getElementById("mySelect");
                selectElement.addEventListener("change", function() {
                    var selectedValue = this.value;
                    if (selectedValue) {
                        var url = "{% url 'abampdb:show-dock' 0 %}".replace("0", selectedValue);
                        window.location.href = url;
                    }
                });
            </script>
            </form>
            </td>
        </tr>


        {% endblock %}

docking/templates/login.html
<div class="container">

    {% block content %} {% load static %}

    <!DOCTYPE html>
    <html lang="en">

    <head>
        <!-- Design by foolishdeveloper.com -->
        <title>Login Page</title>

        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
        <!--Stylesheet-->
        <style media="screen">
            *,
            *:before,
            *:after {
                padding: 0;
                margin: 0;
                box-sizing: border-box;
            }
            
            body {
                background-color: #080710;
            }
            
            .background {
                width: 430px;
                height: 520px;
                position: absolute;
                transform: translate(-50%, -50%);
                left: 50%;
                top: 50%;
            }
            
            .background .shape {
                height: 150px;
                width: 150px;
                position: absolute;
                border-radius: 50%;
            }
            
            .shape:first-child {
                background: linear-gradient( #1845ad, #23a2f6);
                left: -80px;
                top: -0px;
            }
            
            .shape:last-child {
                background: linear-gradient( to right, #ff512f, #f09819);
                right: -30px;
                bottom: -0px;
            }
            
            form {
                height: 410px;
                width: 340px;
                background-color: rgba(255, 255, 255, 0.13);
                position: absolute;
                transform: translate(-50%, -50%);
                top: 50%;
                left: 50%;
                border-radius: 10px;
                backdrop-filter: blur(10px);
                border: 2px solid rgba(255, 255, 255, 0.1);
                box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
                padding: 35px 35px;
            }
            
            form * {
                font-family: 'Poppins', sans-serif;
                color: #ffffff;
                letter-spacing: 0.5px;
                outline: none;
                border: none;
            }
            
            form h3 {
                font-size: 20px;
                font-weight: 400;
                line-height: 42px;
                text-align: center;
            }
            
            label {
                display: block;
                margin-top: 20px;
                font-size: 14px;
                font-weight: 400;
            }
            
            input {
                display: block;
                height: 50px;
                width: 100%;
                background-color: rgba(255, 255, 255, 0.07);
                border-radius: 3px;
                padding: 0 10px;
                margin-top: 8px;
                font-size: 14px;
                font-weight: 300;
            }
            
             ::placeholder {
                color: #e5e5e5;
            }
            
            button {
                margin-top: 20px;
                width: 100%;
                background-color: #ffffff;
                color: #080710;
                padding: 15px 0;
                font-size: 18px;
                font-weight: 600;
                border-radius: 5px;
                cursor: pointer;
            }
        </style>
    </head>

    <body>
        <div class="background">
            <div class="shape"></div>
            <div class="shape"></div>
        </div>
        <form method="post">
            <h3>Login Here</h3>
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" placeholder="Enter Username" id="username" name="username">

            <label for="password">Password</label>
            <input type="password" placeholder="Password" id="password" name="pass">

            <button type="submit">Log In</button>
            <!-- <input type="button" value=""> -->
            <!-- <div class="social">
          <div class="go"><i class="fab fa-google"></i>  Google</div>
          <div class="fb"><i class="fab fa-facebook"></i>  Facebook</div>
        </div> -->
            <a href="{% url 'abampdb:signup' %}">Create a account</a>
        </form>
    </body>

    </html>
</div>
{% endblock %}

<!-- <div class="row justify-content-center">

    <form class="form-inline" method="GET" action="/login/">
        {% csrf_token %}
        <div class="col">
            <input type="text" class="form-control" placeholder="First name" aria-label="First name">
        </div>
        <div class="col">
            <input type="text" class="form-control" placeholder="Last name" aria-label="Last name">
        </div>

        <input name="email" class="form-control" type="text" placeholder="Email">

        <div class="input-group-append">
            <button type="submit" href="{% url 'abampdb:search' %}" class="btn btn-primary btn-lg">Submit</button>
        </div>
    </form>
</div> -->